### PR TITLE
Walmart data collection and log-in issues resolved

### PR DESCRIPTION
**Pull request by pfurbacher**
The "target closed" problem was solved by switching from a forEach to a for/of loop. (Thanks @livgust)

The log-in problem was solved by simply entering the password field -> clicking submit, and then re-entering the password field, and clicking submit again. There is no apparent captcha involved.

### CODE REVIEW

**Comment by harcod** [comment]
I tried running this PR locally and got:

```
Walmart starting.
PAGE LOG: remember me checkbox exists: [object HTMLInputElement]
PAGE LOG: unchecking remember me...
Walmart done.
Error status code [302] returned from schedule request: Found
```

and no results:
```
{
  "version": 1,
  "timestamp": "2021-04-27T194551Z",
  "results": []
}
```

**Comment by pfurbacher** [comment]
Yes, I just caught the mistake -- overly commenting out what I thought was unused code. Made the mistake of not running that branch of the if/else before committing, and finally taking the insistent dog for a long walk. Sorry.

**Comment by harcod** [comment]
The data needs a location **name**

image

**Comment by pfurbacher** [comment]
Asking for approval before committing an update which adds `name` to each location's data:

```
{
      "name": "Walmart Fairhaven, Store #1906",
      "street": "42 Fairhaven Commons Way",
      "city": "Fairhaven",
      "zip": "02719",
      "availability": {...
```

The name mimics what the user would see when navigating the site

Screen Shot 2021-04-29 at 11 43 04 AM

**Comment by harcod** [comment]
I think just **Walmart** will be enough for the name.  We've already established a precedent for removing "store numbers" from the name.  The city will be listed right below Walmart on the location card.

**Comment by pfurbacher** [comment]
Thanks. Committing with name = Walmart

**Comment by harcod** [comment]
@pfurbacher This looks good now in the display.  However, I only got one location with appointments (Hudson).  I re-ran it and got nothing.  When I look on the Walmart site there is availability at LOTS of locations across Massachusetts.  You might want to take a look right now.

**Comment by harcod** [comment]
I looked at it in the debugger... In `ParseAvailability`, the `response` contained `/blocked?url=####=&uuid=####&vid=####&g=a`.  I put that in my browser at walmart.com and it was a **CAPTCHA check**.  I confirmed mu humanity and then continued to run the scraper and it returned ALL of the results.

**Comment by pfurbacher** [comment]
Hmmm, this website is a moving target. Running the scraper yesterday found availability everywhere but a few places. Now, nothing. And I see the same response. This is new. Do you know how to deal with this?

**Comment by pfurbacher** [comment]
Wow. Stepping through the login with Chrome head-full seems to work occasionally (hasn't failed in the 3 times I have done it just now), and then leads to the store list which is quite revamped. Now it lists 43 stores, where it previously listed 25. And it adds details for the user (not useful to us).

**Comment by pfurbacher** [comment]
After having failed to provoke the captcha over many tries, I have made a guess as to where to put the recaptcha code. I have no idea as to whether that is sufficient.

**Comment by pfurbacher** [comment]
@rob, @liv: I have tried (and failed) to get the solveRecaptcha working. I'm stuck. Most times, there appears to be no captcha,  but it fails to get availability. When there is a solved recaptcha, it either times out, or on rare occasion proceeds to get availability. I'm hoping one of you can figure this out.

Note: if you are wondering about  commit `a7ea3b6`, it was a slip of the trackpad tap that picked the wrong branch on upstream to merge with. What a mess having to merge everything correctly after that.

**Comment by pfurbacher** [comment]
Also, since I'm pretty sure this branch has all recent updates from upstream master, I would have expected tests not to fail. But they still are despite the attempt to solve problems with forks.

**Comment by harcod** [comment]
@pfurbacher @livgust.  Now that we have consolidate all of the "large pharmacy sites" including Walmart into a single location card with "assumed" availability, I believe that we can close this PR.

Paul, thanks for all of efforts in attempting to get this scraper to function.

**Comment by pfurbacher** [comment]
I agree that it's time to close it. Will wait for @livgust to comment.

**Pull request closed without merging**
