### PR TITLE
Fix for 404 Page not found for Tufts MC

### PR DESCRIPTION
**Pull request by pfurbacher**
I didn't test by clearing all web data in Chrome. The home page for Tufts MC vaccination registration is `https://www.tuftsmcvaccine.org`. That's the URL in this update.

### CODE REVIEW

**Comment by johnhawkinson** [comment]
This is no longer urgent since the Tufts availability is gone, so we can take a breather.

This PR contains 11 commits and seems to be your whole ZocDoc/Tufts branch. That's not what we want -- you should generally start a new branch for each PR and push that.

Please generate a new PR, something like this

```bash
git checkout master     					# Check out the master branch
git pull     							# Ensure it is up to date
git cherry-pick 07d1a53277925955de45cbfae12eedc5280ed62a	# Cherry-pick the requisite commit from this PR's branch
# Inspect/test to make sure it's right. 
git push pfurbacher						# Specify the proper remote name here
# Go to github and create the PR at the listed URL from the prior command
```

And assuming that's correct (check the "Files Changed" tab on github), then close this one.

**Review by johnhawkinson — CHANGES_REQUESTED** [review]
Oops, should have done this here. See https://github.com/livgust/covid-vaccine-scrapers/pull/199#issuecomment-811832485

**Comment by pfurbacher** [comment]
From my end, I see one commit earlier this morning -- `config.js`. And if I look at the 11 commits in this PR, `07d1a53` (~8 hours ago as of this writing) contains only `config.js`.

I just read through all the diffs in the `Files changed` view -- original (lhs) blank, committed (rhs) TuftsMC. The latter (rhs) all read as expected, what is currently in [master](https://github.com/livgust/covid-vaccine-scrapers).  Not sure why the comparisons are blank on the livgust `master` side. But I think (could be wrong) the thing to look at is the last commit.

For new work on ZocDoc, I created a local branch off the head of `TuftsMC`. What I committed some 8 hours ago was from the head of my local `TuftsMC`.

**Comment by johnhawkinson** [comment]
Hi, Paul!

  I hope this doesn't get too estoteric. I'm trying to be clear, but git can rapidly get confusing, and maybe that's happening here.

> From my end, I see one commit earlier this morning -- `config.js`. And if I look at the 11 commits in this PR, `07d1a53` (~8 hours ago as of this writing) contains only `config.js`.

That's correct, but it is also the problem. This PR contains 11 commits. But the fix is only in the 11th commit. That is the only commit you want to merge to the `master` branch right now, and so it is the only commit that should appear in the PR.

So, you should create a new PR containing only the change you want to merge.
Because there is a 1:1 mapping from git branches to pull requests, you have to create a new branch that contains only that change.

(You could also rebase your existing branch against `master`, depending on whether there are other changes in there, but I dont' think that is a good practice without understanding what will happen, and it is an easy way to make irretrievable errors. Of course you can create a new branch that is identical to your existing branch (with `git branch` or `git checkout -b`) and then rebase _that_. That way you're safe from errors. That's how I generally work.

But in this case you only want that last commit. Hence the "cherry-pick.")

> Not sure why the comparisons are blank on the livgust `master` side. But I think (could be wrong) the thing to look at is the last commit.

From the perspective of semantic review, yes.
But from the perspective of what should be in a pull request and workflow and soforth, that is indicative of the problem I'm asking you to fix by creating a new PR.

Hopefully that's clear.

**Comment by pfurbacher** [comment]
Thanks for clearing that up.

**Comment by pfurbacher** [comment]
Closing this PR. I have created a new one based on John's comments and guidance. Thanks for the help, John.

**Pull request closed without merging**
