### PR TITLE
Fixes 404 due wrong TuftsMC URL in config.js

### PR DESCRIPTION
**Pull request by pfurbacher**
Changes the TuftsMC signUpLink to point to the Tufts vaccine registration home page.

Please close/delete #199

### CODE REVIEW

**Comment by pfurbacher** [comment]
Hmmm, it looks like I was able to close my own PR #199. That was easy enough.

**Review by johnhawkinson — APPROVED** [review]
Looks good, thanks! Not sure why the test is failing now…is it another site?…yes it is. See #205 and soforth.

**Review by tkjones117 — APPROVED** [review]

**Comment by tkjones117** [comment]
@pfurbacher you can get this branch passing tests by doing the following:
```bash
git checkout master # Check out the master branch
git pull # Ensure it is up to date (this will grab a commit that makes the tests pass)
git checkout TuftsMC-404-fix # Check out your feature branch
git rebase master # Replay your commit on top of the new commits from master
git push # update this PR
```

**Comment by johnhawkinson** [comment]
I rebased it and merged it.

**Pull request merged**
