### PR TITLE
log scrapers ip

### PR DESCRIPTION
**Pull request by iann**

### CODE REVIEW

**Comment by johnhawkinson** [comment]
Doesn't this block the world for the HTTPS transaction? Isn't there way to do and log it asynchronously?
Maybe `ifconfig.me`is so reliable we don't care? And if we do it before invoking Puppeteer I guess we have to wait for it, but why not just log it? idk, maybe I'm being silly.

**Comment by iann** [comment]
I can wrap this in a timeout, so that in case the service takes a while it doesn't hold things up.

**Comment by johnhawkinson** [comment]
I just don't get why we don't log it asynchronously whenever it comes back.
Maybe my mental model of asynchronous javascript is deficient—it's definitely handwavy.

**Comment by iann** [comment]
You're totally right. I made is async, by the time the scrapers are done running it would have already resolved or failed.

**Review by johnhawkinson — APPROVED** [review]
Looks good, functions.

**Review by harcod — APPROVED** [review]
I tried the out.json file against the front-end and it still worked fine!

**Pull request merged**
